version: "3"

services:
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DBPassword}
      - MYSQL_USER=${DBUser}
      - MYSQL_PASSWORD=${DBPassword}
      - TZ=Asia/Shanghai
      - MYSQL_DATABASE=${DBDatabase}
    command:
      --max_connections=1000
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --default-authentication-plugin=mysql_native_password
  server:
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    command: ["/app/wait-for.sh", "mysql:3306", "--", "./main"]