name: ci-test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Shutdown Ubuntu MySQL (SUDO)
      run: sudo service mysql stop
    - name: stup up mysql
      uses: mirromutth/mysql-action@v1.1
      with:
        mysql version: 5.7
        mysql database: iftdt
        mysql root password: 123456
        mysql user: gin
        mysql password: 123456
      run:
        mysql -ugin -p123456

    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Test
      run: |
        go test -v ./...
